using System.Diagnostics;
using Google.Protobuf;
using WULib.Core.Extensions;

namespace WULib.Core.Net
{
    internal class RpcEncryption
    {
        /// <summary>
        /// The authenticated <see cref="Session"/>.
        /// </summary>
        private readonly Session _session;

        /// <summary>
        /// The <see cref="Stopwatch"/> that has been running since <see cref="Session.StartupAsync"/>.
        /// </summary>
        private readonly Stopwatch _stopwatch;

        /// <summary>
        /// The session hash for the <see cref="Signature"/> which is 16 randomly generated bytes.
        /// </summary>
        private readonly ByteString _sessionHash;

        /// <summary>
        /// Holds the value that was used in the previous <see cref="BuildLocationFixes"/> iteration.
        /// </summary>
        //private long _lastTimestampSinceStart;

        private readonly Uk27IdGenerator uk27IdGenerator = new Uk27IdGenerator();

        internal RpcEncryption(Session session)
        {
            _session = session;
            _stopwatch = Stopwatch.StartNew();

            var sessionHash = new byte[16];
            session.Random.NextBytes(sessionHash);

            _sessionHash = ByteString.CopyFrom(sessionHash);
            //_lastTimestampSinceStart = 0;
        }

        private long TimestampSinceStartMs => _stopwatch.ElapsedMilliseconds;
    }
}
