// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WUProtos/Networking/Platform/Requests/RegisterPushNotificationMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WUProtos.Networking.Platform.Requests {

  /// <summary>Holder for reflection information generated from WUProtos/Networking/Platform/Requests/RegisterPushNotificationMessage.proto</summary>
  public static partial class RegisterPushNotificationMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for WUProtos/Networking/Platform/Requests/RegisterPushNotificationMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RegisterPushNotificationMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CktXVVByb3Rvcy9OZXR3b3JraW5nL1BsYXRmb3JtL1JlcXVlc3RzL1JlZ2lz",
            "dGVyUHVzaE5vdGlmaWNhdGlvbk1lc3NhZ2UucHJvdG8SJVdVUHJvdG9zLk5l",
            "dHdvcmtpbmcuUGxhdGZvcm0uUmVxdWVzdHMaIldVUHJvdG9zL0RhdGEvVG9r",
            "ZW4vQXBuVG9rZW4ucHJvdG8aIldVUHJvdG9zL0RhdGEvVG9rZW4vR2NtVG9r",
            "ZW4ucHJvdG8ihQEKH1JlZ2lzdGVyUHVzaE5vdGlmaWNhdGlvbk1lc3NhZ2US",
            "MAoJYXBuX3Rva2VuGAEgASgLMh0uV1VQcm90b3MuRGF0YS5Ub2tlbi5BcG5U",
            "b2tlbhIwCglnY21fdG9rZW4YAiABKAsyHS5XVVByb3Rvcy5EYXRhLlRva2Vu",
            "LkdjbVRva2VuYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::WUProtos.Data.Token.ApnTokenReflection.Descriptor, global::WUProtos.Data.Token.GcmTokenReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WUProtos.Networking.Platform.Requests.RegisterPushNotificationMessage), global::WUProtos.Networking.Platform.Requests.RegisterPushNotificationMessage.Parser, new[]{ "ApnToken", "GcmToken" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class RegisterPushNotificationMessage : pb::IMessage<RegisterPushNotificationMessage> {
    private static readonly pb::MessageParser<RegisterPushNotificationMessage> _parser = new pb::MessageParser<RegisterPushNotificationMessage>(() => new RegisterPushNotificationMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RegisterPushNotificationMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WUProtos.Networking.Platform.Requests.RegisterPushNotificationMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegisterPushNotificationMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegisterPushNotificationMessage(RegisterPushNotificationMessage other) : this() {
      apnToken_ = other.apnToken_ != null ? other.apnToken_.Clone() : null;
      gcmToken_ = other.gcmToken_ != null ? other.gcmToken_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegisterPushNotificationMessage Clone() {
      return new RegisterPushNotificationMessage(this);
    }

    /// <summary>Field number for the "apn_token" field.</summary>
    public const int ApnTokenFieldNumber = 1;
    private global::WUProtos.Data.Token.ApnToken apnToken_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WUProtos.Data.Token.ApnToken ApnToken {
      get { return apnToken_; }
      set {
        apnToken_ = value;
      }
    }

    /// <summary>Field number for the "gcm_token" field.</summary>
    public const int GcmTokenFieldNumber = 2;
    private global::WUProtos.Data.Token.GcmToken gcmToken_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WUProtos.Data.Token.GcmToken GcmToken {
      get { return gcmToken_; }
      set {
        gcmToken_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RegisterPushNotificationMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RegisterPushNotificationMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ApnToken, other.ApnToken)) return false;
      if (!object.Equals(GcmToken, other.GcmToken)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (apnToken_ != null) hash ^= ApnToken.GetHashCode();
      if (gcmToken_ != null) hash ^= GcmToken.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (apnToken_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ApnToken);
      }
      if (gcmToken_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(GcmToken);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (apnToken_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ApnToken);
      }
      if (gcmToken_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GcmToken);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RegisterPushNotificationMessage other) {
      if (other == null) {
        return;
      }
      if (other.apnToken_ != null) {
        if (apnToken_ == null) {
          ApnToken = new global::WUProtos.Data.Token.ApnToken();
        }
        ApnToken.MergeFrom(other.ApnToken);
      }
      if (other.gcmToken_ != null) {
        if (gcmToken_ == null) {
          GcmToken = new global::WUProtos.Data.Token.GcmToken();
        }
        GcmToken.MergeFrom(other.GcmToken);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (apnToken_ == null) {
              ApnToken = new global::WUProtos.Data.Token.ApnToken();
            }
            input.ReadMessage(ApnToken);
            break;
          }
          case 18: {
            if (gcmToken_ == null) {
              GcmToken = new global::WUProtos.Data.Token.GcmToken();
            }
            input.ReadMessage(GcmToken);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
