// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WUProtos/Networking/Platform/Responses/DownloadGameMasterTemplatesResponse.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WUProtos.Networking.Platform.Responses {

  /// <summary>Holder for reflection information generated from WUProtos/Networking/Platform/Responses/DownloadGameMasterTemplatesResponse.proto</summary>
  public static partial class DownloadGameMasterTemplatesResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for WUProtos/Networking/Platform/Responses/DownloadGameMasterTemplatesResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DownloadGameMasterTemplatesResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ClBXVVByb3Rvcy9OZXR3b3JraW5nL1BsYXRmb3JtL1Jlc3BvbnNlcy9Eb3du",
            "bG9hZEdhbWVNYXN0ZXJUZW1wbGF0ZXNSZXNwb25zZS5wcm90bxImV1VQcm90",
            "b3MuTmV0d29ya2luZy5QbGF0Zm9ybS5SZXNwb25zZXMi6QMKI0Rvd25sb2Fk",
            "R2FtZU1hc3RlclRlbXBsYXRlc1Jlc3BvbnNlEmIKBnJlc3VsdBgBIAEoDjJS",
            "LldVUHJvdG9zLk5ldHdvcmtpbmcuUGxhdGZvcm0uUmVzcG9uc2VzLkRvd25s",
            "b2FkR2FtZU1hc3RlclRlbXBsYXRlc1Jlc3BvbnNlLlJlc3VsdBJ2Cgh0ZW1w",
            "bGF0ZRgCIAMoCzJkLldVUHJvdG9zLk5ldHdvcmtpbmcuUGxhdGZvcm0uUmVz",
            "cG9uc2VzLkRvd25sb2FkR2FtZU1hc3RlclRlbXBsYXRlc1Jlc3BvbnNlLkNs",
            "aWVudEdhbWVNYXN0ZXJUZW1wbGF0ZRIYChBkZWxldGVkX3RlbXBsYXRlGAMg",
            "AygJEhAKCGJhdGNoX2lkGAQgASgEEhMKC3BhZ2Vfb2Zmc2V0GAUgASgFGj0K",
            "GENsaWVudEdhbWVNYXN0ZXJUZW1wbGF0ZRITCgt0ZW1wbGF0ZV9pZBgBIAEo",
            "CRIMCgRkYXRhGAIgASgMImYKBlJlc3VsdBIJCgVVTlNFVBAAEgwKCENPTVBM",
            "RVRFEAESEAoMTU9SRV9SRVNVTFRTEAISFQoRQkFUQ0hfSURfTk9UX0xJVkUQ",
            "AxIaChZJTlZBTElEX0JBU0lTX0JBVENIX0lEEARiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WUProtos.Networking.Platform.Responses.DownloadGameMasterTemplatesResponse), global::WUProtos.Networking.Platform.Responses.DownloadGameMasterTemplatesResponse.Parser, new[]{ "Result", "Template", "DeletedTemplate", "BatchId", "PageOffset" }, null, new[]{ typeof(global::WUProtos.Networking.Platform.Responses.DownloadGameMasterTemplatesResponse.Types.Result) }, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::WUProtos.Networking.Platform.Responses.DownloadGameMasterTemplatesResponse.Types.ClientGameMasterTemplate), global::WUProtos.Networking.Platform.Responses.DownloadGameMasterTemplatesResponse.Types.ClientGameMasterTemplate.Parser, new[]{ "TemplateId", "Data" }, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class DownloadGameMasterTemplatesResponse : pb::IMessage<DownloadGameMasterTemplatesResponse> {
    private static readonly pb::MessageParser<DownloadGameMasterTemplatesResponse> _parser = new pb::MessageParser<DownloadGameMasterTemplatesResponse>(() => new DownloadGameMasterTemplatesResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DownloadGameMasterTemplatesResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WUProtos.Networking.Platform.Responses.DownloadGameMasterTemplatesResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DownloadGameMasterTemplatesResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DownloadGameMasterTemplatesResponse(DownloadGameMasterTemplatesResponse other) : this() {
      result_ = other.result_;
      template_ = other.template_.Clone();
      deletedTemplate_ = other.deletedTemplate_.Clone();
      batchId_ = other.batchId_;
      pageOffset_ = other.pageOffset_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DownloadGameMasterTemplatesResponse Clone() {
      return new DownloadGameMasterTemplatesResponse(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::WUProtos.Networking.Platform.Responses.DownloadGameMasterTemplatesResponse.Types.Result result_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WUProtos.Networking.Platform.Responses.DownloadGameMasterTemplatesResponse.Types.Result Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "template" field.</summary>
    public const int TemplateFieldNumber = 2;
    private static readonly pb::FieldCodec<global::WUProtos.Networking.Platform.Responses.DownloadGameMasterTemplatesResponse.Types.ClientGameMasterTemplate> _repeated_template_codec
        = pb::FieldCodec.ForMessage(18, global::WUProtos.Networking.Platform.Responses.DownloadGameMasterTemplatesResponse.Types.ClientGameMasterTemplate.Parser);
    private readonly pbc::RepeatedField<global::WUProtos.Networking.Platform.Responses.DownloadGameMasterTemplatesResponse.Types.ClientGameMasterTemplate> template_ = new pbc::RepeatedField<global::WUProtos.Networking.Platform.Responses.DownloadGameMasterTemplatesResponse.Types.ClientGameMasterTemplate>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::WUProtos.Networking.Platform.Responses.DownloadGameMasterTemplatesResponse.Types.ClientGameMasterTemplate> Template {
      get { return template_; }
    }

    /// <summary>Field number for the "deleted_template" field.</summary>
    public const int DeletedTemplateFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_deletedTemplate_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> deletedTemplate_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> DeletedTemplate {
      get { return deletedTemplate_; }
    }

    /// <summary>Field number for the "batch_id" field.</summary>
    public const int BatchIdFieldNumber = 4;
    private ulong batchId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong BatchId {
      get { return batchId_; }
      set {
        batchId_ = value;
      }
    }

    /// <summary>Field number for the "page_offset" field.</summary>
    public const int PageOffsetFieldNumber = 5;
    private int pageOffset_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PageOffset {
      get { return pageOffset_; }
      set {
        pageOffset_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DownloadGameMasterTemplatesResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DownloadGameMasterTemplatesResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if(!template_.Equals(other.template_)) return false;
      if(!deletedTemplate_.Equals(other.deletedTemplate_)) return false;
      if (BatchId != other.BatchId) return false;
      if (PageOffset != other.PageOffset) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      hash ^= template_.GetHashCode();
      hash ^= deletedTemplate_.GetHashCode();
      if (BatchId != 0UL) hash ^= BatchId.GetHashCode();
      if (PageOffset != 0) hash ^= PageOffset.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      template_.WriteTo(output, _repeated_template_codec);
      deletedTemplate_.WriteTo(output, _repeated_deletedTemplate_codec);
      if (BatchId != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(BatchId);
      }
      if (PageOffset != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(PageOffset);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      size += template_.CalculateSize(_repeated_template_codec);
      size += deletedTemplate_.CalculateSize(_repeated_deletedTemplate_codec);
      if (BatchId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(BatchId);
      }
      if (PageOffset != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PageOffset);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DownloadGameMasterTemplatesResponse other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
      template_.Add(other.template_);
      deletedTemplate_.Add(other.deletedTemplate_);
      if (other.BatchId != 0UL) {
        BatchId = other.BatchId;
      }
      if (other.PageOffset != 0) {
        PageOffset = other.PageOffset;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = (global::WUProtos.Networking.Platform.Responses.DownloadGameMasterTemplatesResponse.Types.Result) input.ReadEnum();
            break;
          }
          case 18: {
            template_.AddEntriesFrom(input, _repeated_template_codec);
            break;
          }
          case 26: {
            deletedTemplate_.AddEntriesFrom(input, _repeated_deletedTemplate_codec);
            break;
          }
          case 32: {
            BatchId = input.ReadUInt64();
            break;
          }
          case 40: {
            PageOffset = input.ReadInt32();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the DownloadGameMasterTemplatesResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Result {
        [pbr::OriginalName("UNSET")] Unset = 0,
        [pbr::OriginalName("COMPLETE")] Complete = 1,
        [pbr::OriginalName("MORE_RESULTS")] MoreResults = 2,
        [pbr::OriginalName("BATCH_ID_NOT_LIVE")] BatchIdNotLive = 3,
        [pbr::OriginalName("INVALID_BASIS_BATCH_ID")] InvalidBasisBatchId = 4,
      }

      public sealed partial class ClientGameMasterTemplate : pb::IMessage<ClientGameMasterTemplate> {
        private static readonly pb::MessageParser<ClientGameMasterTemplate> _parser = new pb::MessageParser<ClientGameMasterTemplate>(() => new ClientGameMasterTemplate());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<ClientGameMasterTemplate> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::WUProtos.Networking.Platform.Responses.DownloadGameMasterTemplatesResponse.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ClientGameMasterTemplate() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ClientGameMasterTemplate(ClientGameMasterTemplate other) : this() {
          templateId_ = other.templateId_;
          data_ = other.data_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ClientGameMasterTemplate Clone() {
          return new ClientGameMasterTemplate(this);
        }

        /// <summary>Field number for the "template_id" field.</summary>
        public const int TemplateIdFieldNumber = 1;
        private string templateId_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string TemplateId {
          get { return templateId_; }
          set {
            templateId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "data" field.</summary>
        public const int DataFieldNumber = 2;
        private pb::ByteString data_ = pb::ByteString.Empty;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pb::ByteString Data {
          get { return data_; }
          set {
            data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as ClientGameMasterTemplate);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(ClientGameMasterTemplate other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (TemplateId != other.TemplateId) return false;
          if (Data != other.Data) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (TemplateId.Length != 0) hash ^= TemplateId.GetHashCode();
          if (Data.Length != 0) hash ^= Data.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (TemplateId.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(TemplateId);
          }
          if (Data.Length != 0) {
            output.WriteRawTag(18);
            output.WriteBytes(Data);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (TemplateId.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(TemplateId);
          }
          if (Data.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(ClientGameMasterTemplate other) {
          if (other == null) {
            return;
          }
          if (other.TemplateId.Length != 0) {
            TemplateId = other.TemplateId;
          }
          if (other.Data.Length != 0) {
            Data = other.Data;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                TemplateId = input.ReadString();
                break;
              }
              case 18: {
                Data = input.ReadBytes();
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
