// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WUProtos/Networking/Responses/AdminReadSkusResponse.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WUProtos.Networking.Responses {

  /// <summary>Holder for reflection information generated from WUProtos/Networking/Responses/AdminReadSkusResponse.proto</summary>
  public static partial class AdminReadSkusResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for WUProtos/Networking/Responses/AdminReadSkusResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AdminReadSkusResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjlXVVByb3Rvcy9OZXR3b3JraW5nL1Jlc3BvbnNlcy9BZG1pblJlYWRTa3Vz",
            "UmVzcG9uc2UucHJvdG8SHVdVUHJvdG9zLk5ldHdvcmtpbmcuUmVzcG9uc2Vz",
            "GhtXVVByb3Rvcy9EYXRhL1NrdURhdGEucHJvdG8iPAoVQWRtaW5SZWFkU2t1",
            "c1Jlc3BvbnNlEiMKA3NrdRgBIAMoCzIWLldVUHJvdG9zLkRhdGEuU2t1RGF0",
            "YWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::WUProtos.Data.SkuDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WUProtos.Networking.Responses.AdminReadSkusResponse), global::WUProtos.Networking.Responses.AdminReadSkusResponse.Parser, new[]{ "Sku" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class AdminReadSkusResponse : pb::IMessage<AdminReadSkusResponse> {
    private static readonly pb::MessageParser<AdminReadSkusResponse> _parser = new pb::MessageParser<AdminReadSkusResponse>(() => new AdminReadSkusResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AdminReadSkusResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WUProtos.Networking.Responses.AdminReadSkusResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AdminReadSkusResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AdminReadSkusResponse(AdminReadSkusResponse other) : this() {
      sku_ = other.sku_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AdminReadSkusResponse Clone() {
      return new AdminReadSkusResponse(this);
    }

    /// <summary>Field number for the "sku" field.</summary>
    public const int SkuFieldNumber = 1;
    private static readonly pb::FieldCodec<global::WUProtos.Data.SkuData> _repeated_sku_codec
        = pb::FieldCodec.ForMessage(10, global::WUProtos.Data.SkuData.Parser);
    private readonly pbc::RepeatedField<global::WUProtos.Data.SkuData> sku_ = new pbc::RepeatedField<global::WUProtos.Data.SkuData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::WUProtos.Data.SkuData> Sku {
      get { return sku_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AdminReadSkusResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AdminReadSkusResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!sku_.Equals(other.sku_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= sku_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      sku_.WriteTo(output, _repeated_sku_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += sku_.CalculateSize(_repeated_sku_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AdminReadSkusResponse other) {
      if (other == null) {
        return;
      }
      sku_.Add(other.sku_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            sku_.AddEntriesFrom(input, _repeated_sku_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
