// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WUProtos/Networking/Responses/CastSpellForGrowingResponse.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WUProtos.Networking.Responses {

  /// <summary>Holder for reflection information generated from WUProtos/Networking/Responses/CastSpellForGrowingResponse.proto</summary>
  public static partial class CastSpellForGrowingResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for WUProtos/Networking/Responses/CastSpellForGrowingResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CastSpellForGrowingResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cj9XVVByb3Rvcy9OZXR3b3JraW5nL1Jlc3BvbnNlcy9DYXN0U3BlbGxGb3JH",
            "cm93aW5nUmVzcG9uc2UucHJvdG8SHVdVUHJvdG9zLk5ldHdvcmtpbmcuUmVz",
            "cG9uc2VzIpACChtDYXN0U3BlbGxGb3JHcm93aW5nUmVzcG9uc2USUQoGc3Rh",
            "dHVzGAEgASgOMkEuV1VQcm90b3MuTmV0d29ya2luZy5SZXNwb25zZXMuQ2Fz",
            "dFNwZWxsRm9yR3Jvd2luZ1Jlc3BvbnNlLlN0YXR1cyKdAQoGU3RhdHVzEgkK",
            "BVVOU0VUEAASCwoHU1VDQ0VTUxABEgsKB1RPT19GQVIQAhIOCgpQT0lfQ0xP",
            "U0VEEAMSFAoQRkVBVFVSRV9ESVNBQkxFRBAEEg8KC0lOVkFMSURfUE9UEAUS",
            "GwoXTk9UX0VOT1VHSF9TUEVMTF9FTkVSR1kQBhIaChZOT19HUk9XSU5HX0lO",
            "X1BST0dSRVNTEAdiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WUProtos.Networking.Responses.CastSpellForGrowingResponse), global::WUProtos.Networking.Responses.CastSpellForGrowingResponse.Parser, new[]{ "Status" }, null, new[]{ typeof(global::WUProtos.Networking.Responses.CastSpellForGrowingResponse.Types.Status) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CastSpellForGrowingResponse : pb::IMessage<CastSpellForGrowingResponse> {
    private static readonly pb::MessageParser<CastSpellForGrowingResponse> _parser = new pb::MessageParser<CastSpellForGrowingResponse>(() => new CastSpellForGrowingResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CastSpellForGrowingResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WUProtos.Networking.Responses.CastSpellForGrowingResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CastSpellForGrowingResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CastSpellForGrowingResponse(CastSpellForGrowingResponse other) : this() {
      status_ = other.status_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CastSpellForGrowingResponse Clone() {
      return new CastSpellForGrowingResponse(this);
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 1;
    private global::WUProtos.Networking.Responses.CastSpellForGrowingResponse.Types.Status status_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WUProtos.Networking.Responses.CastSpellForGrowingResponse.Types.Status Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CastSpellForGrowingResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CastSpellForGrowingResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Status != other.Status) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Status != 0) hash ^= Status.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Status != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Status != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CastSpellForGrowingResponse other) {
      if (other == null) {
        return;
      }
      if (other.Status != 0) {
        Status = other.Status;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Status = (global::WUProtos.Networking.Responses.CastSpellForGrowingResponse.Types.Status) input.ReadEnum();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the CastSpellForGrowingResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Status {
        [pbr::OriginalName("UNSET")] Unset = 0,
        [pbr::OriginalName("SUCCESS")] Success = 1,
        [pbr::OriginalName("TOO_FAR")] TooFar = 2,
        [pbr::OriginalName("POI_CLOSED")] PoiClosed = 3,
        [pbr::OriginalName("FEATURE_DISABLED")] FeatureDisabled = 4,
        [pbr::OriginalName("INVALID_POT")] InvalidPot = 5,
        [pbr::OriginalName("NOT_ENOUGH_SPELL_ENERGY")] NotEnoughSpellEnergy = 6,
        [pbr::OriginalName("NO_GROWING_IN_PROGRESS")] NoGrowingInProgress = 7,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
