// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WUProtos/Networking/Responses/GetFortressFlooNetworkStatisticsResponse.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WUProtos.Networking.Responses {

  /// <summary>Holder for reflection information generated from WUProtos/Networking/Responses/GetFortressFlooNetworkStatisticsResponse.proto</summary>
  public static partial class GetFortressFlooNetworkStatisticsResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for WUProtos/Networking/Responses/GetFortressFlooNetworkStatisticsResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GetFortressFlooNetworkStatisticsResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkxXVVByb3Rvcy9OZXR3b3JraW5nL1Jlc3BvbnNlcy9HZXRGb3J0cmVzc0Zs",
            "b29OZXR3b3JrU3RhdGlzdGljc1Jlc3BvbnNlLnByb3RvEh1XVVByb3Rvcy5O",
            "ZXR3b3JraW5nLlJlc3BvbnNlcxoxV1VQcm90b3MvRGF0YS9GbG9vTmV0d29y",
            "a0ZvcnRyZXNzU3RhdGlzdGljcy5wcm90byKdAQooR2V0Rm9ydHJlc3NGbG9v",
            "TmV0d29ya1N0YXRpc3RpY3NSZXNwb25zZRJJChNmb3J0cmVzc19zdGF0aXN0",
            "aWNzGAEgASgLMiwuV1VQcm90b3MuRGF0YS5GbG9vTmV0d29ya0ZvcnRyZXNz",
            "U3RhdGlzdGljcxImCh50ZW1wX25leHRfYWRkX3B0c190aW1lc3RhbXBfbXMY",
            "AiABKANiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::WUProtos.Data.FlooNetworkFortressStatisticsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WUProtos.Networking.Responses.GetFortressFlooNetworkStatisticsResponse), global::WUProtos.Networking.Responses.GetFortressFlooNetworkStatisticsResponse.Parser, new[]{ "FortressStatistics", "TempNextAddPtsTimestampMs" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GetFortressFlooNetworkStatisticsResponse : pb::IMessage<GetFortressFlooNetworkStatisticsResponse> {
    private static readonly pb::MessageParser<GetFortressFlooNetworkStatisticsResponse> _parser = new pb::MessageParser<GetFortressFlooNetworkStatisticsResponse>(() => new GetFortressFlooNetworkStatisticsResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetFortressFlooNetworkStatisticsResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WUProtos.Networking.Responses.GetFortressFlooNetworkStatisticsResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetFortressFlooNetworkStatisticsResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetFortressFlooNetworkStatisticsResponse(GetFortressFlooNetworkStatisticsResponse other) : this() {
      fortressStatistics_ = other.fortressStatistics_ != null ? other.fortressStatistics_.Clone() : null;
      tempNextAddPtsTimestampMs_ = other.tempNextAddPtsTimestampMs_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetFortressFlooNetworkStatisticsResponse Clone() {
      return new GetFortressFlooNetworkStatisticsResponse(this);
    }

    /// <summary>Field number for the "fortress_statistics" field.</summary>
    public const int FortressStatisticsFieldNumber = 1;
    private global::WUProtos.Data.FlooNetworkFortressStatistics fortressStatistics_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WUProtos.Data.FlooNetworkFortressStatistics FortressStatistics {
      get { return fortressStatistics_; }
      set {
        fortressStatistics_ = value;
      }
    }

    /// <summary>Field number for the "temp_next_add_pts_timestamp_ms" field.</summary>
    public const int TempNextAddPtsTimestampMsFieldNumber = 2;
    private long tempNextAddPtsTimestampMs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long TempNextAddPtsTimestampMs {
      get { return tempNextAddPtsTimestampMs_; }
      set {
        tempNextAddPtsTimestampMs_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetFortressFlooNetworkStatisticsResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetFortressFlooNetworkStatisticsResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(FortressStatistics, other.FortressStatistics)) return false;
      if (TempNextAddPtsTimestampMs != other.TempNextAddPtsTimestampMs) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (fortressStatistics_ != null) hash ^= FortressStatistics.GetHashCode();
      if (TempNextAddPtsTimestampMs != 0L) hash ^= TempNextAddPtsTimestampMs.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (fortressStatistics_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(FortressStatistics);
      }
      if (TempNextAddPtsTimestampMs != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(TempNextAddPtsTimestampMs);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (fortressStatistics_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FortressStatistics);
      }
      if (TempNextAddPtsTimestampMs != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TempNextAddPtsTimestampMs);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetFortressFlooNetworkStatisticsResponse other) {
      if (other == null) {
        return;
      }
      if (other.fortressStatistics_ != null) {
        if (fortressStatistics_ == null) {
          FortressStatistics = new global::WUProtos.Data.FlooNetworkFortressStatistics();
        }
        FortressStatistics.MergeFrom(other.FortressStatistics);
      }
      if (other.TempNextAddPtsTimestampMs != 0L) {
        TempNextAddPtsTimestampMs = other.TempNextAddPtsTimestampMs;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (fortressStatistics_ == null) {
              FortressStatistics = new global::WUProtos.Data.FlooNetworkFortressStatistics();
            }
            input.ReadMessage(FortressStatistics);
            break;
          }
          case 16: {
            TempNextAddPtsTimestampMs = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
