// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WUProtos/Networking/Responses/PrestigePageResponse.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WUProtos.Networking.Responses {

  /// <summary>Holder for reflection information generated from WUProtos/Networking/Responses/PrestigePageResponse.proto</summary>
  public static partial class PrestigePageResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for WUProtos/Networking/Responses/PrestigePageResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PrestigePageResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjhXVVByb3Rvcy9OZXR3b3JraW5nL1Jlc3BvbnNlcy9QcmVzdGlnZVBhZ2VS",
            "ZXNwb25zZS5wcm90bxIdV1VQcm90b3MuTmV0d29ya2luZy5SZXNwb25zZXMi",
            "sQEKFFByZXN0aWdlUGFnZVJlc3BvbnNlEkoKBnN0YXR1cxgBIAEoDjI6LldV",
            "UHJvdG9zLk5ldHdvcmtpbmcuUmVzcG9uc2VzLlByZXN0aWdlUGFnZVJlc3Bv",
            "bnNlLlN0YXR1cxIaChJjb2xsZWN0aW9uX3BhZ2VfaWQYAiABKAkiMQoGU3Rh",
            "dHVzEgsKB1VOS05PV04QABILCgdTVUNDRVNTEAESDQoJTk9UX1JFQURZEAJi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WUProtos.Networking.Responses.PrestigePageResponse), global::WUProtos.Networking.Responses.PrestigePageResponse.Parser, new[]{ "Status", "CollectionPageId" }, null, new[]{ typeof(global::WUProtos.Networking.Responses.PrestigePageResponse.Types.Status) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PrestigePageResponse : pb::IMessage<PrestigePageResponse> {
    private static readonly pb::MessageParser<PrestigePageResponse> _parser = new pb::MessageParser<PrestigePageResponse>(() => new PrestigePageResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PrestigePageResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WUProtos.Networking.Responses.PrestigePageResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PrestigePageResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PrestigePageResponse(PrestigePageResponse other) : this() {
      status_ = other.status_;
      collectionPageId_ = other.collectionPageId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PrestigePageResponse Clone() {
      return new PrestigePageResponse(this);
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 1;
    private global::WUProtos.Networking.Responses.PrestigePageResponse.Types.Status status_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WUProtos.Networking.Responses.PrestigePageResponse.Types.Status Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "collection_page_id" field.</summary>
    public const int CollectionPageIdFieldNumber = 2;
    private string collectionPageId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CollectionPageId {
      get { return collectionPageId_; }
      set {
        collectionPageId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PrestigePageResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PrestigePageResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Status != other.Status) return false;
      if (CollectionPageId != other.CollectionPageId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Status != 0) hash ^= Status.GetHashCode();
      if (CollectionPageId.Length != 0) hash ^= CollectionPageId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Status != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Status);
      }
      if (CollectionPageId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CollectionPageId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Status != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (CollectionPageId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CollectionPageId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PrestigePageResponse other) {
      if (other == null) {
        return;
      }
      if (other.Status != 0) {
        Status = other.Status;
      }
      if (other.CollectionPageId.Length != 0) {
        CollectionPageId = other.CollectionPageId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Status = (global::WUProtos.Networking.Responses.PrestigePageResponse.Types.Status) input.ReadEnum();
            break;
          }
          case 18: {
            CollectionPageId = input.ReadString();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the PrestigePageResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Status {
        [pbr::OriginalName("UNKNOWN")] Unknown = 0,
        [pbr::OriginalName("SUCCESS")] Success = 1,
        [pbr::OriginalName("NOT_READY")] NotReady = 2,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
