// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WUProtos/Networking/Requests/Messages/CastSpellForGrowingMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WUProtos.Networking.Requests.Messages {

  /// <summary>Holder for reflection information generated from WUProtos/Networking/Requests/Messages/CastSpellForGrowingMessage.proto</summary>
  public static partial class CastSpellForGrowingMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for WUProtos/Networking/Requests/Messages/CastSpellForGrowingMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CastSpellForGrowingMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkZXVVByb3Rvcy9OZXR3b3JraW5nL1JlcXVlc3RzL01lc3NhZ2VzL0Nhc3RT",
            "cGVsbEZvckdyb3dpbmdNZXNzYWdlLnByb3RvEiVXVVByb3Rvcy5OZXR3b3Jr",
            "aW5nLlJlcXVlc3RzLk1lc3NhZ2VzIlYKGkNhc3RTcGVsbEZvckdyb3dpbmdN",
            "ZXNzYWdlEhIKCm91dHBvc3RfaWQYASABKAkSDgoGcG90X2lkGAIgASgJEhQK",
            "DHNwZWxsX2VuZXJneRgDIAEoBWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WUProtos.Networking.Requests.Messages.CastSpellForGrowingMessage), global::WUProtos.Networking.Requests.Messages.CastSpellForGrowingMessage.Parser, new[]{ "OutpostId", "PotId", "SpellEnergy" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CastSpellForGrowingMessage : pb::IMessage<CastSpellForGrowingMessage> {
    private static readonly pb::MessageParser<CastSpellForGrowingMessage> _parser = new pb::MessageParser<CastSpellForGrowingMessage>(() => new CastSpellForGrowingMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CastSpellForGrowingMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WUProtos.Networking.Requests.Messages.CastSpellForGrowingMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CastSpellForGrowingMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CastSpellForGrowingMessage(CastSpellForGrowingMessage other) : this() {
      outpostId_ = other.outpostId_;
      potId_ = other.potId_;
      spellEnergy_ = other.spellEnergy_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CastSpellForGrowingMessage Clone() {
      return new CastSpellForGrowingMessage(this);
    }

    /// <summary>Field number for the "outpost_id" field.</summary>
    public const int OutpostIdFieldNumber = 1;
    private string outpostId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string OutpostId {
      get { return outpostId_; }
      set {
        outpostId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pot_id" field.</summary>
    public const int PotIdFieldNumber = 2;
    private string potId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PotId {
      get { return potId_; }
      set {
        potId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "spell_energy" field.</summary>
    public const int SpellEnergyFieldNumber = 3;
    private int spellEnergy_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SpellEnergy {
      get { return spellEnergy_; }
      set {
        spellEnergy_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CastSpellForGrowingMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CastSpellForGrowingMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OutpostId != other.OutpostId) return false;
      if (PotId != other.PotId) return false;
      if (SpellEnergy != other.SpellEnergy) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (OutpostId.Length != 0) hash ^= OutpostId.GetHashCode();
      if (PotId.Length != 0) hash ^= PotId.GetHashCode();
      if (SpellEnergy != 0) hash ^= SpellEnergy.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (OutpostId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(OutpostId);
      }
      if (PotId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PotId);
      }
      if (SpellEnergy != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(SpellEnergy);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (OutpostId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OutpostId);
      }
      if (PotId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PotId);
      }
      if (SpellEnergy != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SpellEnergy);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CastSpellForGrowingMessage other) {
      if (other == null) {
        return;
      }
      if (other.OutpostId.Length != 0) {
        OutpostId = other.OutpostId;
      }
      if (other.PotId.Length != 0) {
        PotId = other.PotId;
      }
      if (other.SpellEnergy != 0) {
        SpellEnergy = other.SpellEnergy;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            OutpostId = input.ReadString();
            break;
          }
          case 18: {
            PotId = input.ReadString();
            break;
          }
          case 24: {
            SpellEnergy = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
