// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WUProtos/Networking/Requests/Messages/DbgGrantLootCollectionMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WUProtos.Networking.Requests.Messages {

  /// <summary>Holder for reflection information generated from WUProtos/Networking/Requests/Messages/DbgGrantLootCollectionMessage.proto</summary>
  public static partial class DbgGrantLootCollectionMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for WUProtos/Networking/Requests/Messages/DbgGrantLootCollectionMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DbgGrantLootCollectionMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CklXVVByb3Rvcy9OZXR3b3JraW5nL1JlcXVlc3RzL01lc3NhZ2VzL0RiZ0dy",
            "YW50TG9vdENvbGxlY3Rpb25NZXNzYWdlLnByb3RvEiVXVVByb3Rvcy5OZXR3",
            "b3JraW5nLlJlcXVlc3RzLk1lc3NhZ2VzGiNXVVByb3Rvcy9EYXRhL0xvb3Qv",
            "TG9vdFJld2FyZC5wcm90byLzAQodRGJnR3JhbnRMb290Q29sbGVjdGlvbk1l",
            "c3NhZ2USRgoPbG9vdF9jb2xsZWN0aW9uGAEgASgLMi0uV1VQcm90b3MuRGF0",
            "YS5Mb290Lkxvb3RSZXdhcmQuTG9vdENvbGxlY3Rpb24SZgoMcmVxdWVzdF90",
            "eXBlGAIgASgOMlAuV1VQcm90b3MuTmV0d29ya2luZy5SZXF1ZXN0cy5NZXNz",
            "YWdlcy5EYmdHcmFudExvb3RDb2xsZWN0aW9uTWVzc2FnZS5SZXF1ZXN0VHlw",
            "ZSIiCgtSZXF1ZXN0VHlwZRIHCgNBREQQABIKCgZSRU1PVkUQAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::WUProtos.Data.Loot.LootRewardReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WUProtos.Networking.Requests.Messages.DbgGrantLootCollectionMessage), global::WUProtos.Networking.Requests.Messages.DbgGrantLootCollectionMessage.Parser, new[]{ "LootCollection", "RequestType" }, null, new[]{ typeof(global::WUProtos.Networking.Requests.Messages.DbgGrantLootCollectionMessage.Types.RequestType) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class DbgGrantLootCollectionMessage : pb::IMessage<DbgGrantLootCollectionMessage> {
    private static readonly pb::MessageParser<DbgGrantLootCollectionMessage> _parser = new pb::MessageParser<DbgGrantLootCollectionMessage>(() => new DbgGrantLootCollectionMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DbgGrantLootCollectionMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WUProtos.Networking.Requests.Messages.DbgGrantLootCollectionMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DbgGrantLootCollectionMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DbgGrantLootCollectionMessage(DbgGrantLootCollectionMessage other) : this() {
      lootCollection_ = other.lootCollection_ != null ? other.lootCollection_.Clone() : null;
      requestType_ = other.requestType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DbgGrantLootCollectionMessage Clone() {
      return new DbgGrantLootCollectionMessage(this);
    }

    /// <summary>Field number for the "loot_collection" field.</summary>
    public const int LootCollectionFieldNumber = 1;
    private global::WUProtos.Data.Loot.LootReward.Types.LootCollection lootCollection_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WUProtos.Data.Loot.LootReward.Types.LootCollection LootCollection {
      get { return lootCollection_; }
      set {
        lootCollection_ = value;
      }
    }

    /// <summary>Field number for the "request_type" field.</summary>
    public const int RequestTypeFieldNumber = 2;
    private global::WUProtos.Networking.Requests.Messages.DbgGrantLootCollectionMessage.Types.RequestType requestType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WUProtos.Networking.Requests.Messages.DbgGrantLootCollectionMessage.Types.RequestType RequestType {
      get { return requestType_; }
      set {
        requestType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DbgGrantLootCollectionMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DbgGrantLootCollectionMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(LootCollection, other.LootCollection)) return false;
      if (RequestType != other.RequestType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (lootCollection_ != null) hash ^= LootCollection.GetHashCode();
      if (RequestType != 0) hash ^= RequestType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (lootCollection_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(LootCollection);
      }
      if (RequestType != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) RequestType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (lootCollection_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LootCollection);
      }
      if (RequestType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) RequestType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DbgGrantLootCollectionMessage other) {
      if (other == null) {
        return;
      }
      if (other.lootCollection_ != null) {
        if (lootCollection_ == null) {
          LootCollection = new global::WUProtos.Data.Loot.LootReward.Types.LootCollection();
        }
        LootCollection.MergeFrom(other.LootCollection);
      }
      if (other.RequestType != 0) {
        RequestType = other.RequestType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (lootCollection_ == null) {
              LootCollection = new global::WUProtos.Data.Loot.LootReward.Types.LootCollection();
            }
            input.ReadMessage(LootCollection);
            break;
          }
          case 16: {
            RequestType = (global::WUProtos.Networking.Requests.Messages.DbgGrantLootCollectionMessage.Types.RequestType) input.ReadEnum();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the DbgGrantLootCollectionMessage message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum RequestType {
        [pbr::OriginalName("ADD")] Add = 0,
        [pbr::OriginalName("REMOVE")] Remove = 1,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
