// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WUProtos/Networking/Requests/Messages/DbgStartEncounterMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WUProtos.Networking.Requests.Messages {

  /// <summary>Holder for reflection information generated from WUProtos/Networking/Requests/Messages/DbgStartEncounterMessage.proto</summary>
  public static partial class DbgStartEncounterMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for WUProtos/Networking/Requests/Messages/DbgStartEncounterMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DbgStartEncounterMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkRXVVByb3Rvcy9OZXR3b3JraW5nL1JlcXVlc3RzL01lc3NhZ2VzL0RiZ1N0",
            "YXJ0RW5jb3VudGVyTWVzc2FnZS5wcm90bxIlV1VQcm90b3MuTmV0d29ya2lu",
            "Zy5SZXF1ZXN0cy5NZXNzYWdlcyJhChhEYmdTdGFydEVuY291bnRlck1lc3Nh",
            "Z2USGAoQZW5jb3VudGVyX2dtdF9pZBgBIAEoCRIcChRzdGFydGluZ19zdGFn",
            "ZV9pbmRleBgCIAEoBRINCgVsZXZlbBgDIAEoBWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WUProtos.Networking.Requests.Messages.DbgStartEncounterMessage), global::WUProtos.Networking.Requests.Messages.DbgStartEncounterMessage.Parser, new[]{ "EncounterGmtId", "StartingStageIndex", "Level" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class DbgStartEncounterMessage : pb::IMessage<DbgStartEncounterMessage> {
    private static readonly pb::MessageParser<DbgStartEncounterMessage> _parser = new pb::MessageParser<DbgStartEncounterMessage>(() => new DbgStartEncounterMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DbgStartEncounterMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WUProtos.Networking.Requests.Messages.DbgStartEncounterMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DbgStartEncounterMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DbgStartEncounterMessage(DbgStartEncounterMessage other) : this() {
      encounterGmtId_ = other.encounterGmtId_;
      startingStageIndex_ = other.startingStageIndex_;
      level_ = other.level_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DbgStartEncounterMessage Clone() {
      return new DbgStartEncounterMessage(this);
    }

    /// <summary>Field number for the "encounter_gmt_id" field.</summary>
    public const int EncounterGmtIdFieldNumber = 1;
    private string encounterGmtId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string EncounterGmtId {
      get { return encounterGmtId_; }
      set {
        encounterGmtId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "starting_stage_index" field.</summary>
    public const int StartingStageIndexFieldNumber = 2;
    private int startingStageIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StartingStageIndex {
      get { return startingStageIndex_; }
      set {
        startingStageIndex_ = value;
      }
    }

    /// <summary>Field number for the "level" field.</summary>
    public const int LevelFieldNumber = 3;
    private int level_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DbgStartEncounterMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DbgStartEncounterMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EncounterGmtId != other.EncounterGmtId) return false;
      if (StartingStageIndex != other.StartingStageIndex) return false;
      if (Level != other.Level) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (EncounterGmtId.Length != 0) hash ^= EncounterGmtId.GetHashCode();
      if (StartingStageIndex != 0) hash ^= StartingStageIndex.GetHashCode();
      if (Level != 0) hash ^= Level.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (EncounterGmtId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(EncounterGmtId);
      }
      if (StartingStageIndex != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(StartingStageIndex);
      }
      if (Level != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Level);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (EncounterGmtId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EncounterGmtId);
      }
      if (StartingStageIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StartingStageIndex);
      }
      if (Level != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DbgStartEncounterMessage other) {
      if (other == null) {
        return;
      }
      if (other.EncounterGmtId.Length != 0) {
        EncounterGmtId = other.EncounterGmtId;
      }
      if (other.StartingStageIndex != 0) {
        StartingStageIndex = other.StartingStageIndex;
      }
      if (other.Level != 0) {
        Level = other.Level;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            EncounterGmtId = input.ReadString();
            break;
          }
          case 16: {
            StartingStageIndex = input.ReadInt32();
            break;
          }
          case 24: {
            Level = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
