// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WUProtos/Networking/Requests/Messages/MapAbilityStartMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WUProtos.Networking.Requests.Messages {

  /// <summary>Holder for reflection information generated from WUProtos/Networking/Requests/Messages/MapAbilityStartMessage.proto</summary>
  public static partial class MapAbilityStartMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for WUProtos/Networking/Requests/Messages/MapAbilityStartMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MapAbilityStartMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkJXVVByb3Rvcy9OZXR3b3JraW5nL1JlcXVlc3RzL01lc3NhZ2VzL01hcEFi",
            "aWxpdHlTdGFydE1lc3NhZ2UucHJvdG8SJVdVUHJvdG9zLk5ldHdvcmtpbmcu",
            "UmVxdWVzdHMuTWVzc2FnZXMaIFdVUHJvdG9zL01hcC9NYXBDb29yZGluYXRl",
            "LnByb3RvIqIBChZNYXBBYmlsaXR5U3RhcnRNZXNzYWdlEhoKEm1hcF9hYmls",
            "aXR5X2dtdF9pZBgBIAEoCRIZCg9wbGF5ZXJfbmlja25hbWUYAiABKAlIABI1",
            "Cg5tYXBfY29vcmRpbmF0ZRgDIAEoCzIbLldVUHJvdG9zLk1hcC5NYXBDb29y",
            "ZGluYXRlSAASEAoGbW9iX2lkGAQgASgMSABCCAoGVGFyZ2V0YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::WUProtos.Map.MapCoordinateReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WUProtos.Networking.Requests.Messages.MapAbilityStartMessage), global::WUProtos.Networking.Requests.Messages.MapAbilityStartMessage.Parser, new[]{ "MapAbilityGmtId", "PlayerNickname", "MapCoordinate", "MobId" }, new[]{ "Target" }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class MapAbilityStartMessage : pb::IMessage<MapAbilityStartMessage> {
    private static readonly pb::MessageParser<MapAbilityStartMessage> _parser = new pb::MessageParser<MapAbilityStartMessage>(() => new MapAbilityStartMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MapAbilityStartMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WUProtos.Networking.Requests.Messages.MapAbilityStartMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MapAbilityStartMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MapAbilityStartMessage(MapAbilityStartMessage other) : this() {
      mapAbilityGmtId_ = other.mapAbilityGmtId_;
      switch (other.TargetCase) {
        case TargetOneofCase.PlayerNickname:
          PlayerNickname = other.PlayerNickname;
          break;
        case TargetOneofCase.MapCoordinate:
          MapCoordinate = other.MapCoordinate.Clone();
          break;
        case TargetOneofCase.MobId:
          MobId = other.MobId;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MapAbilityStartMessage Clone() {
      return new MapAbilityStartMessage(this);
    }

    /// <summary>Field number for the "map_ability_gmt_id" field.</summary>
    public const int MapAbilityGmtIdFieldNumber = 1;
    private string mapAbilityGmtId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MapAbilityGmtId {
      get { return mapAbilityGmtId_; }
      set {
        mapAbilityGmtId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "player_nickname" field.</summary>
    public const int PlayerNicknameFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PlayerNickname {
      get { return targetCase_ == TargetOneofCase.PlayerNickname ? (string) target_ : ""; }
      set {
        target_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        targetCase_ = TargetOneofCase.PlayerNickname;
      }
    }

    /// <summary>Field number for the "map_coordinate" field.</summary>
    public const int MapCoordinateFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WUProtos.Map.MapCoordinate MapCoordinate {
      get { return targetCase_ == TargetOneofCase.MapCoordinate ? (global::WUProtos.Map.MapCoordinate) target_ : null; }
      set {
        target_ = value;
        targetCase_ = value == null ? TargetOneofCase.None : TargetOneofCase.MapCoordinate;
      }
    }

    /// <summary>Field number for the "mob_id" field.</summary>
    public const int MobIdFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString MobId {
      get { return targetCase_ == TargetOneofCase.MobId ? (pb::ByteString) target_ : pb::ByteString.Empty; }
      set {
        target_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        targetCase_ = TargetOneofCase.MobId;
      }
    }

    private object target_;
    /// <summary>Enum of possible cases for the "Target" oneof.</summary>
    public enum TargetOneofCase {
      None = 0,
      PlayerNickname = 2,
      MapCoordinate = 3,
      MobId = 4,
    }
    private TargetOneofCase targetCase_ = TargetOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TargetOneofCase TargetCase {
      get { return targetCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearTarget() {
      targetCase_ = TargetOneofCase.None;
      target_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MapAbilityStartMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MapAbilityStartMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MapAbilityGmtId != other.MapAbilityGmtId) return false;
      if (PlayerNickname != other.PlayerNickname) return false;
      if (!object.Equals(MapCoordinate, other.MapCoordinate)) return false;
      if (MobId != other.MobId) return false;
      if (TargetCase != other.TargetCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MapAbilityGmtId.Length != 0) hash ^= MapAbilityGmtId.GetHashCode();
      if (targetCase_ == TargetOneofCase.PlayerNickname) hash ^= PlayerNickname.GetHashCode();
      if (targetCase_ == TargetOneofCase.MapCoordinate) hash ^= MapCoordinate.GetHashCode();
      if (targetCase_ == TargetOneofCase.MobId) hash ^= MobId.GetHashCode();
      hash ^= (int) targetCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MapAbilityGmtId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MapAbilityGmtId);
      }
      if (targetCase_ == TargetOneofCase.PlayerNickname) {
        output.WriteRawTag(18);
        output.WriteString(PlayerNickname);
      }
      if (targetCase_ == TargetOneofCase.MapCoordinate) {
        output.WriteRawTag(26);
        output.WriteMessage(MapCoordinate);
      }
      if (targetCase_ == TargetOneofCase.MobId) {
        output.WriteRawTag(34);
        output.WriteBytes(MobId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MapAbilityGmtId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MapAbilityGmtId);
      }
      if (targetCase_ == TargetOneofCase.PlayerNickname) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PlayerNickname);
      }
      if (targetCase_ == TargetOneofCase.MapCoordinate) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MapCoordinate);
      }
      if (targetCase_ == TargetOneofCase.MobId) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(MobId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MapAbilityStartMessage other) {
      if (other == null) {
        return;
      }
      if (other.MapAbilityGmtId.Length != 0) {
        MapAbilityGmtId = other.MapAbilityGmtId;
      }
      switch (other.TargetCase) {
        case TargetOneofCase.PlayerNickname:
          PlayerNickname = other.PlayerNickname;
          break;
        case TargetOneofCase.MapCoordinate:
          if (MapCoordinate == null) {
            MapCoordinate = new global::WUProtos.Map.MapCoordinate();
          }
          MapCoordinate.MergeFrom(other.MapCoordinate);
          break;
        case TargetOneofCase.MobId:
          MobId = other.MobId;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            MapAbilityGmtId = input.ReadString();
            break;
          }
          case 18: {
            PlayerNickname = input.ReadString();
            break;
          }
          case 26: {
            global::WUProtos.Map.MapCoordinate subBuilder = new global::WUProtos.Map.MapCoordinate();
            if (targetCase_ == TargetOneofCase.MapCoordinate) {
              subBuilder.MergeFrom(MapCoordinate);
            }
            input.ReadMessage(subBuilder);
            MapCoordinate = subBuilder;
            break;
          }
          case 34: {
            MobId = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
