// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WUProtos/Data/Client/ClientHouse.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WUProtos.Data.Client {

  /// <summary>Holder for reflection information generated from WUProtos/Data/Client/ClientHouse.proto</summary>
  public static partial class ClientHouseReflection {

    #region Descriptor
    /// <summary>File descriptor for WUProtos/Data/Client/ClientHouse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClientHouseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiZXVVByb3Rvcy9EYXRhL0NsaWVudC9DbGllbnRIb3VzZS5wcm90bxIUV1VQ",
            "cm90b3MuRGF0YS5DbGllbnQaGVdVUHJvdG9zL0RhdGEvQ29sb3IucHJvdG8i",
            "ywEKC0NsaWVudEhvdXNlEgwKBG5hbWUYASABKAkSEwoLZGVzY3JpcHRpb24Y",
            "AiABKAkSDAoEaWNvbhgDIAEoCRIPCgdhbmltX2luGAQgASgJEhEKCWFuaW1f",
            "bG9vcBgFIAEoCRIQCghhbmltX291dBgGIAEoCRIjCgVjb2xvchgHIAEoCzIU",
            "LldVUHJvdG9zLkRhdGEuQ29sb3ISFAoMc291bmRfc2VsZWN0GAggASgJEhoK",
            "EmludHJvX3NvdW5kX3NlbGVjdBgJIAEoCWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::WUProtos.Data.ColorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WUProtos.Data.Client.ClientHouse), global::WUProtos.Data.Client.ClientHouse.Parser, new[]{ "Name", "Description", "Icon", "AnimIn", "AnimLoop", "AnimOut", "Color", "SoundSelect", "IntroSoundSelect" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ClientHouse : pb::IMessage<ClientHouse> {
    private static readonly pb::MessageParser<ClientHouse> _parser = new pb::MessageParser<ClientHouse>(() => new ClientHouse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ClientHouse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WUProtos.Data.Client.ClientHouseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientHouse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientHouse(ClientHouse other) : this() {
      name_ = other.name_;
      description_ = other.description_;
      icon_ = other.icon_;
      animIn_ = other.animIn_;
      animLoop_ = other.animLoop_;
      animOut_ = other.animOut_;
      color_ = other.color_ != null ? other.color_.Clone() : null;
      soundSelect_ = other.soundSelect_;
      introSoundSelect_ = other.introSoundSelect_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientHouse Clone() {
      return new ClientHouse(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 2;
    private string description_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "icon" field.</summary>
    public const int IconFieldNumber = 3;
    private string icon_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Icon {
      get { return icon_; }
      set {
        icon_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "anim_in" field.</summary>
    public const int AnimInFieldNumber = 4;
    private string animIn_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AnimIn {
      get { return animIn_; }
      set {
        animIn_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "anim_loop" field.</summary>
    public const int AnimLoopFieldNumber = 5;
    private string animLoop_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AnimLoop {
      get { return animLoop_; }
      set {
        animLoop_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "anim_out" field.</summary>
    public const int AnimOutFieldNumber = 6;
    private string animOut_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AnimOut {
      get { return animOut_; }
      set {
        animOut_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "color" field.</summary>
    public const int ColorFieldNumber = 7;
    private global::WUProtos.Data.Color color_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WUProtos.Data.Color Color {
      get { return color_; }
      set {
        color_ = value;
      }
    }

    /// <summary>Field number for the "sound_select" field.</summary>
    public const int SoundSelectFieldNumber = 8;
    private string soundSelect_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SoundSelect {
      get { return soundSelect_; }
      set {
        soundSelect_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "intro_sound_select" field.</summary>
    public const int IntroSoundSelectFieldNumber = 9;
    private string introSoundSelect_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IntroSoundSelect {
      get { return introSoundSelect_; }
      set {
        introSoundSelect_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ClientHouse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ClientHouse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Description != other.Description) return false;
      if (Icon != other.Icon) return false;
      if (AnimIn != other.AnimIn) return false;
      if (AnimLoop != other.AnimLoop) return false;
      if (AnimOut != other.AnimOut) return false;
      if (!object.Equals(Color, other.Color)) return false;
      if (SoundSelect != other.SoundSelect) return false;
      if (IntroSoundSelect != other.IntroSoundSelect) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Description.Length != 0) hash ^= Description.GetHashCode();
      if (Icon.Length != 0) hash ^= Icon.GetHashCode();
      if (AnimIn.Length != 0) hash ^= AnimIn.GetHashCode();
      if (AnimLoop.Length != 0) hash ^= AnimLoop.GetHashCode();
      if (AnimOut.Length != 0) hash ^= AnimOut.GetHashCode();
      if (color_ != null) hash ^= Color.GetHashCode();
      if (SoundSelect.Length != 0) hash ^= SoundSelect.GetHashCode();
      if (IntroSoundSelect.Length != 0) hash ^= IntroSoundSelect.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Description);
      }
      if (Icon.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Icon);
      }
      if (AnimIn.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(AnimIn);
      }
      if (AnimLoop.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(AnimLoop);
      }
      if (AnimOut.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(AnimOut);
      }
      if (color_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Color);
      }
      if (SoundSelect.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(SoundSelect);
      }
      if (IntroSoundSelect.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(IntroSoundSelect);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Description.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      if (Icon.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Icon);
      }
      if (AnimIn.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AnimIn);
      }
      if (AnimLoop.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AnimLoop);
      }
      if (AnimOut.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AnimOut);
      }
      if (color_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Color);
      }
      if (SoundSelect.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SoundSelect);
      }
      if (IntroSoundSelect.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IntroSoundSelect);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ClientHouse other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Description.Length != 0) {
        Description = other.Description;
      }
      if (other.Icon.Length != 0) {
        Icon = other.Icon;
      }
      if (other.AnimIn.Length != 0) {
        AnimIn = other.AnimIn;
      }
      if (other.AnimLoop.Length != 0) {
        AnimLoop = other.AnimLoop;
      }
      if (other.AnimOut.Length != 0) {
        AnimOut = other.AnimOut;
      }
      if (other.color_ != null) {
        if (color_ == null) {
          Color = new global::WUProtos.Data.Color();
        }
        Color.MergeFrom(other.Color);
      }
      if (other.SoundSelect.Length != 0) {
        SoundSelect = other.SoundSelect;
      }
      if (other.IntroSoundSelect.Length != 0) {
        IntroSoundSelect = other.IntroSoundSelect;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Description = input.ReadString();
            break;
          }
          case 26: {
            Icon = input.ReadString();
            break;
          }
          case 34: {
            AnimIn = input.ReadString();
            break;
          }
          case 42: {
            AnimLoop = input.ReadString();
            break;
          }
          case 50: {
            AnimOut = input.ReadString();
            break;
          }
          case 58: {
            if (color_ == null) {
              Color = new global::WUProtos.Data.Color();
            }
            input.ReadMessage(Color);
            break;
          }
          case 66: {
            SoundSelect = input.ReadString();
            break;
          }
          case 74: {
            IntroSoundSelect = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
