// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WUProtos/Data/Event/DownstreamActionEventParams.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WUProtos.Data.Event {

  /// <summary>Holder for reflection information generated from WUProtos/Data/Event/DownstreamActionEventParams.proto</summary>
  public static partial class DownstreamActionEventParamsReflection {

    #region Descriptor
    /// <summary>File descriptor for WUProtos/Data/Event/DownstreamActionEventParams.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DownstreamActionEventParamsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjVXVVByb3Rvcy9EYXRhL0V2ZW50L0Rvd25zdHJlYW1BY3Rpb25FdmVudFBh",
            "cmFtcy5wcm90bxITV1VQcm90b3MuRGF0YS5FdmVudCJNChtEb3duc3RyZWFt",
            "QWN0aW9uRXZlbnRQYXJhbXMSDwoHbWV0aG9kcxgBIAMoDRIQCghwYXlsb2Fk",
            "cxgCIAMoDBILCgNpZHMYAyADKARiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WUProtos.Data.Event.DownstreamActionEventParams), global::WUProtos.Data.Event.DownstreamActionEventParams.Parser, new[]{ "Methods", "Payloads", "Ids" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class DownstreamActionEventParams : pb::IMessage<DownstreamActionEventParams> {
    private static readonly pb::MessageParser<DownstreamActionEventParams> _parser = new pb::MessageParser<DownstreamActionEventParams>(() => new DownstreamActionEventParams());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DownstreamActionEventParams> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WUProtos.Data.Event.DownstreamActionEventParamsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DownstreamActionEventParams() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DownstreamActionEventParams(DownstreamActionEventParams other) : this() {
      methods_ = other.methods_.Clone();
      payloads_ = other.payloads_.Clone();
      ids_ = other.ids_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DownstreamActionEventParams Clone() {
      return new DownstreamActionEventParams(this);
    }

    /// <summary>Field number for the "methods" field.</summary>
    public const int MethodsFieldNumber = 1;
    private static readonly pb::FieldCodec<uint> _repeated_methods_codec
        = pb::FieldCodec.ForUInt32(10);
    private readonly pbc::RepeatedField<uint> methods_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<uint> Methods {
      get { return methods_; }
    }

    /// <summary>Field number for the "payloads" field.</summary>
    public const int PayloadsFieldNumber = 2;
    private static readonly pb::FieldCodec<pb::ByteString> _repeated_payloads_codec
        = pb::FieldCodec.ForBytes(18);
    private readonly pbc::RepeatedField<pb::ByteString> payloads_ = new pbc::RepeatedField<pb::ByteString>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<pb::ByteString> Payloads {
      get { return payloads_; }
    }

    /// <summary>Field number for the "ids" field.</summary>
    public const int IdsFieldNumber = 3;
    private static readonly pb::FieldCodec<ulong> _repeated_ids_codec
        = pb::FieldCodec.ForUInt64(26);
    private readonly pbc::RepeatedField<ulong> ids_ = new pbc::RepeatedField<ulong>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<ulong> Ids {
      get { return ids_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DownstreamActionEventParams);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DownstreamActionEventParams other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!methods_.Equals(other.methods_)) return false;
      if(!payloads_.Equals(other.payloads_)) return false;
      if(!ids_.Equals(other.ids_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= methods_.GetHashCode();
      hash ^= payloads_.GetHashCode();
      hash ^= ids_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      methods_.WriteTo(output, _repeated_methods_codec);
      payloads_.WriteTo(output, _repeated_payloads_codec);
      ids_.WriteTo(output, _repeated_ids_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += methods_.CalculateSize(_repeated_methods_codec);
      size += payloads_.CalculateSize(_repeated_payloads_codec);
      size += ids_.CalculateSize(_repeated_ids_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DownstreamActionEventParams other) {
      if (other == null) {
        return;
      }
      methods_.Add(other.methods_);
      payloads_.Add(other.payloads_);
      ids_.Add(other.ids_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 8: {
            methods_.AddEntriesFrom(input, _repeated_methods_codec);
            break;
          }
          case 18: {
            payloads_.AddEntriesFrom(input, _repeated_payloads_codec);
            break;
          }
          case 26:
          case 24: {
            ids_.AddEntriesFrom(input, _repeated_ids_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
