// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WUProtos/Data/EmailOpts.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WUProtos.Data {

  /// <summary>Holder for reflection information generated from WUProtos/Data/EmailOpts.proto</summary>
  public static partial class EmailOptsReflection {

    #region Descriptor
    /// <summary>File descriptor for WUProtos/Data/EmailOpts.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EmailOptsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1XVVByb3Rvcy9EYXRhL0VtYWlsT3B0cy5wcm90bxINV1VQcm90b3MuRGF0",
            "YSJtCglFbWFpbE9wdHMSGgoSc2VuZF91cGRhdGVfZW1haWxzGAEgASgIEiAK",
            "GHNlbmRfd2JfbWFya2V0aW5nX2VtYWlscxgCIAEoCBIiChplbWFpbF9vcHRz",
            "X2xhc3RfdXBkYXRlZF9tcxgDIAEoA2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WUProtos.Data.EmailOpts), global::WUProtos.Data.EmailOpts.Parser, new[]{ "SendUpdateEmails", "SendWbMarketingEmails", "EmailOptsLastUpdatedMs" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class EmailOpts : pb::IMessage<EmailOpts> {
    private static readonly pb::MessageParser<EmailOpts> _parser = new pb::MessageParser<EmailOpts>(() => new EmailOpts());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EmailOpts> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WUProtos.Data.EmailOptsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EmailOpts() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EmailOpts(EmailOpts other) : this() {
      sendUpdateEmails_ = other.sendUpdateEmails_;
      sendWbMarketingEmails_ = other.sendWbMarketingEmails_;
      emailOptsLastUpdatedMs_ = other.emailOptsLastUpdatedMs_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EmailOpts Clone() {
      return new EmailOpts(this);
    }

    /// <summary>Field number for the "send_update_emails" field.</summary>
    public const int SendUpdateEmailsFieldNumber = 1;
    private bool sendUpdateEmails_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool SendUpdateEmails {
      get { return sendUpdateEmails_; }
      set {
        sendUpdateEmails_ = value;
      }
    }

    /// <summary>Field number for the "send_wb_marketing_emails" field.</summary>
    public const int SendWbMarketingEmailsFieldNumber = 2;
    private bool sendWbMarketingEmails_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool SendWbMarketingEmails {
      get { return sendWbMarketingEmails_; }
      set {
        sendWbMarketingEmails_ = value;
      }
    }

    /// <summary>Field number for the "email_opts_last_updated_ms" field.</summary>
    public const int EmailOptsLastUpdatedMsFieldNumber = 3;
    private long emailOptsLastUpdatedMs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long EmailOptsLastUpdatedMs {
      get { return emailOptsLastUpdatedMs_; }
      set {
        emailOptsLastUpdatedMs_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EmailOpts);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EmailOpts other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SendUpdateEmails != other.SendUpdateEmails) return false;
      if (SendWbMarketingEmails != other.SendWbMarketingEmails) return false;
      if (EmailOptsLastUpdatedMs != other.EmailOptsLastUpdatedMs) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (SendUpdateEmails != false) hash ^= SendUpdateEmails.GetHashCode();
      if (SendWbMarketingEmails != false) hash ^= SendWbMarketingEmails.GetHashCode();
      if (EmailOptsLastUpdatedMs != 0L) hash ^= EmailOptsLastUpdatedMs.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (SendUpdateEmails != false) {
        output.WriteRawTag(8);
        output.WriteBool(SendUpdateEmails);
      }
      if (SendWbMarketingEmails != false) {
        output.WriteRawTag(16);
        output.WriteBool(SendWbMarketingEmails);
      }
      if (EmailOptsLastUpdatedMs != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(EmailOptsLastUpdatedMs);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (SendUpdateEmails != false) {
        size += 1 + 1;
      }
      if (SendWbMarketingEmails != false) {
        size += 1 + 1;
      }
      if (EmailOptsLastUpdatedMs != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(EmailOptsLastUpdatedMs);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EmailOpts other) {
      if (other == null) {
        return;
      }
      if (other.SendUpdateEmails != false) {
        SendUpdateEmails = other.SendUpdateEmails;
      }
      if (other.SendWbMarketingEmails != false) {
        SendWbMarketingEmails = other.SendWbMarketingEmails;
      }
      if (other.EmailOptsLastUpdatedMs != 0L) {
        EmailOptsLastUpdatedMs = other.EmailOptsLastUpdatedMs;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SendUpdateEmails = input.ReadBool();
            break;
          }
          case 16: {
            SendWbMarketingEmails = input.ReadBool();
            break;
          }
          case 24: {
            EmailOptsLastUpdatedMs = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
