// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WUProtos/Enums/ActiveEngagement.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WUProtos.Enums {

  /// <summary>Holder for reflection information generated from WUProtos/Enums/ActiveEngagement.proto</summary>
  public static partial class ActiveEngagementReflection {

    #region Descriptor
    /// <summary>File descriptor for WUProtos/Enums/ActiveEngagement.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ActiveEngagementReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVXVVByb3Rvcy9FbnVtcy9BY3RpdmVFbmdhZ2VtZW50LnByb3RvEg5XVVBy",
            "b3Rvcy5FbnVtcypUChBBY3RpdmVFbmdhZ2VtZW50EhsKF0FDVElWRV9FTkdB",
            "R0VNRU5UX1VOU0VUEAASEgoOTU9CX0lTX0VOR0FHRUQQARIPCgtNT0JfSVNf",
            "RlJFRRACYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::WUProtos.Enums.ActiveEngagement), }, null));
    }
    #endregion

  }
  #region Enums
  public enum ActiveEngagement {
    [pbr::OriginalName("ACTIVE_ENGAGEMENT_UNSET")] Unset = 0,
    [pbr::OriginalName("MOB_IS_ENGAGED")] MobIsEngaged = 1,
    [pbr::OriginalName("MOB_IS_FREE")] MobIsFree = 2,
  }

  #endregion

}

#endregion Designer generated code
