// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WUProtos/Enums/ChallengeRpcStatus.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WUProtos.Enums {

  /// <summary>Holder for reflection information generated from WUProtos/Enums/ChallengeRpcStatus.proto</summary>
  public static partial class ChallengeRpcStatusReflection {

    #region Descriptor
    /// <summary>File descriptor for WUProtos/Enums/ChallengeRpcStatus.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ChallengeRpcStatusReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CidXVVByb3Rvcy9FbnVtcy9DaGFsbGVuZ2VScGNTdGF0dXMucHJvdG8SDldV",
            "UHJvdG9zLkVudW1zKs4CChJDaGFsbGVuZ2VScGNTdGF0dXMSGQoVQ0hBTExF",
            "TkdFX1JQQ19VTktOT1dOEAASGQoVQ0hBTExFTkdFX1JQQ19TVUNDRVNTEAES",
            "HgoaQ0hBTExFTkdFX1JQQ19PVVRfT0ZfUkFOR0UQAhIgChxDSEFMTEVOR0Vf",
            "UlBDX05PVF9JTl9DSEFNQkVSEAMSJAogQ0hBTExFTkdFX1JQQ19BTFJFQURZ",
            "X0lOX0NIQU1CRVIQBBIoCiRDSEFMTEVOR0VfUlBDX0NBTk5PVF9QTEFDRV9S",
            "VU5FU1RPTkUQBRIcChhDSEFMTEVOR0VfUlBDX1BPSV9DTE9TRUQQBhImCiJD",
            "SEFMTEVOR0VfUlBDX0ZPUlRSRVNTX0lOX0NPT0xET1dOEAcSKgomQ0hBTExF",
            "TkdFX1JQQ19DQU5OT1RfQ0hBTkdFX1BST0ZFU1NJT04QCGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::WUProtos.Enums.ChallengeRpcStatus), }, null));
    }
    #endregion

  }
  #region Enums
  public enum ChallengeRpcStatus {
    [pbr::OriginalName("CHALLENGE_RPC_UNKNOWN")] ChallengeRpcUnknown = 0,
    [pbr::OriginalName("CHALLENGE_RPC_SUCCESS")] ChallengeRpcSuccess = 1,
    [pbr::OriginalName("CHALLENGE_RPC_OUT_OF_RANGE")] ChallengeRpcOutOfRange = 2,
    [pbr::OriginalName("CHALLENGE_RPC_NOT_IN_CHAMBER")] ChallengeRpcNotInChamber = 3,
    [pbr::OriginalName("CHALLENGE_RPC_ALREADY_IN_CHAMBER")] ChallengeRpcAlreadyInChamber = 4,
    [pbr::OriginalName("CHALLENGE_RPC_CANNOT_PLACE_RUNESTONE")] ChallengeRpcCannotPlaceRunestone = 5,
    [pbr::OriginalName("CHALLENGE_RPC_POI_CLOSED")] ChallengeRpcPoiClosed = 6,
    [pbr::OriginalName("CHALLENGE_RPC_FORTRESS_IN_COOLDOWN")] ChallengeRpcFortressInCooldown = 7,
    [pbr::OriginalName("CHALLENGE_RPC_CANNOT_CHANGE_PROFESSION")] ChallengeRpcCannotChangeProfession = 8,
  }

  #endregion

}

#endregion Designer generated code
