// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WUProtos/Enums/EqualityOperator.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WUProtos.Enums {

  /// <summary>Holder for reflection information generated from WUProtos/Enums/EqualityOperator.proto</summary>
  public static partial class EqualityOperatorReflection {

    #region Descriptor
    /// <summary>File descriptor for WUProtos/Enums/EqualityOperator.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EqualityOperatorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVXVVByb3Rvcy9FbnVtcy9FcXVhbGl0eU9wZXJhdG9yLnByb3RvEg5XVVBy",
            "b3Rvcy5FbnVtcypPChBFcXVhbGl0eU9wZXJhdG9yEhsKF0VRVUFMSVRZX09Q",
            "RVJBVE9SX1VOU0VUEAASDAoISVNfRVFVQUwQARIQCgxJU19OT1RfRVFVQUwQ",
            "AmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::WUProtos.Enums.EqualityOperator), }, null));
    }
    #endregion

  }
  #region Enums
  public enum EqualityOperator {
    [pbr::OriginalName("EQUALITY_OPERATOR_UNSET")] Unset = 0,
    [pbr::OriginalName("IS_EQUAL")] IsEqual = 1,
    [pbr::OriginalName("IS_NOT_EQUAL")] IsNotEqual = 2,
  }

  #endregion

}

#endregion Designer generated code
