// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WUProtos/Enums/LexiconMetricIds.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WUProtos.Enums {

  /// <summary>Holder for reflection information generated from WUProtos/Enums/LexiconMetricIds.proto</summary>
  public static partial class LexiconMetricIdsReflection {

    #region Descriptor
    /// <summary>File descriptor for WUProtos/Enums/LexiconMetricIds.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LexiconMetricIdsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVXVVByb3Rvcy9FbnVtcy9MZXhpY29uTWV0cmljSWRzLnByb3RvEg5XVVBy",
            "b3Rvcy5FbnVtcyo+ChBMZXhpY29uTWV0cmljSWRzEhMKD1VOU0VUX01FVFJJ",
            "Q19JRBAAEhUKEUdFTkVSSUNfTUVUUklDX0lEEAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::WUProtos.Enums.LexiconMetricIds), }, null));
    }
    #endregion

  }
  #region Enums
  public enum LexiconMetricIds {
    [pbr::OriginalName("UNSET_METRIC_ID")] UnsetMetricId = 0,
    [pbr::OriginalName("GENERIC_METRIC_ID")] GenericMetricId = 1,
  }

  #endregion

}

#endregion Designer generated code
