// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WUProtos/Enums/MasterNoteGesture.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WUProtos.Enums {

  /// <summary>Holder for reflection information generated from WUProtos/Enums/MasterNoteGesture.proto</summary>
  public static partial class MasterNoteGestureReflection {

    #region Descriptor
    /// <summary>File descriptor for WUProtos/Enums/MasterNoteGesture.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MasterNoteGestureReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiZXVVByb3Rvcy9FbnVtcy9NYXN0ZXJOb3RlR2VzdHVyZS5wcm90bxIOV1VQ",
            "cm90b3MuRW51bXMq2gEKEU1hc3Rlck5vdGVHZXN0dXJlEhAKDEdFU1RVUkVf",
            "Tk9ORRAAEhYKEkdFU1RVUkVfSE9SSVpPTlRBTBABEhQKEEdFU1RVUkVfVkVS",
            "VElDQUwQAhIVChFHRVNUVVJFX0NMT0NLV0lTRRADEh0KGUdFU1RVUkVfQ09V",
            "TlRFUl9DTE9DS1dJU0UQBBIVChFHRVNUVVJFX1BJTkNIX09VVBAFEhQKEEdF",
            "U1RVUkVfUElOQ0hfSU4QBhIPCgtHRVNUVVJFX1RBUBAHEhEKDUdFU1RVUkVf",
            "U0hBS0UQCGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::WUProtos.Enums.MasterNoteGesture), }, null));
    }
    #endregion

  }
  #region Enums
  public enum MasterNoteGesture {
    [pbr::OriginalName("GESTURE_NONE")] GestureNone = 0,
    [pbr::OriginalName("GESTURE_HORIZONTAL")] GestureHorizontal = 1,
    [pbr::OriginalName("GESTURE_VERTICAL")] GestureVertical = 2,
    [pbr::OriginalName("GESTURE_CLOCKWISE")] GestureClockwise = 3,
    [pbr::OriginalName("GESTURE_COUNTER_CLOCKWISE")] GestureCounterClockwise = 4,
    [pbr::OriginalName("GESTURE_PINCH_OUT")] GesturePinchOut = 5,
    [pbr::OriginalName("GESTURE_PINCH_IN")] GesturePinchIn = 6,
    [pbr::OriginalName("GESTURE_TAP")] GestureTap = 7,
    [pbr::OriginalName("GESTURE_SHAKE")] GestureShake = 8,
  }

  #endregion

}

#endregion Designer generated code
