// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WUProtos/Enums/NotificationState.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WUProtos.Enums {

  /// <summary>Holder for reflection information generated from WUProtos/Enums/NotificationState.proto</summary>
  public static partial class NotificationStateReflection {

    #region Descriptor
    /// <summary>File descriptor for WUProtos/Enums/NotificationState.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NotificationStateReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiZXVVByb3Rvcy9FbnVtcy9Ob3RpZmljYXRpb25TdGF0ZS5wcm90bxIOV1VQ",
            "cm90b3MuRW51bXMqMAoRTm90aWZpY2F0aW9uU3RhdGUSDwoLVU5TRVRfU1RB",
            "VEUQABIKCgZWSUVXRUQQAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::WUProtos.Enums.NotificationState), }, null));
    }
    #endregion

  }
  #region Enums
  public enum NotificationState {
    [pbr::OriginalName("UNSET_STATE")] UnsetState = 0,
    [pbr::OriginalName("VIEWED")] Viewed = 1,
  }

  #endregion

}

#endregion Designer generated code
